repos:
  - name: Rust
    url: https://github.com/rust-unofficial/awesome-rust
    icon: ğŸ¦€
  - name: Golang
    url: https://github.com/avelino/awesome-go
    icon: ğŸ¹
  - name: JavaScript
    url:
      - https://github.com/sorrycc/awesome-javascript
      - https://github.com/uhub/awesome-javascript
    icon: ğŸŸ¨
  - name: NodeJS
    url: https://github.com/sindresorhus/awesome-nodejs
    icon: ğŸŸ©
  - name: iOS
    url: https://github.com/vsouza/awesome-ios
    icon: ğŸ
  - name: Xamarin
    url: https://github.com/XamSome/awesome-xamarin
    icon: ğŸ“±
  - name: Python
    url: https://github.com/vinta/awesome-python
    icon: ğŸ
  - name: Vue
    url: https://github.com/vuejs/awesome-vue
    icon: ğŸ––
  - name: Flutter
    url: https://github.com/Solido/awesome-flutter
    icon: ğŸ¦
  - name: CPP
    url: https://github.com/fffaraz/awesome-cpp
    icon: â•
  - name: Java
    url: https://github.com/akullpp/awesome-java
    icon: â˜•
  - name: Swift
    url: https://github.com/matteocrippa/awesome-swift
    icon: ğŸ¦
  - name: dotNET
    url: https://github.com/quozd/awesome-dotnet
    icon: ğŸ¯
  - name: Ruby
    url: https://github.com/markets/awesome-ruby
    icon: ğŸ’
  - name: TensorFlow
    url: https://github.com/jtoy/awesome-tensorflow
    icon: ğŸ¤–
  - name: NeoVim
    url: https://github.com/rockerBOO/awesome-neovim
    icon: ğŸ“
  - name: TailwindCSS
    url: https://github.com/aniftyco/awesome-tailwindcss
    icon: ğŸŒ¬ï¸
  - name: Elixir
    url: https://github.com/h4cc/awesome-elixir
    icon: âš—ï¸
  - name: Laravel
    url: https://github.com/chiraggude/awesome-laravel
    icon: ğŸ› ï¸
  - name: Kotlin
    url: https://github.com/KotlinBy/awesome-kotlin
    icon: ğŸ…º
  - name: Scala
    url: https://github.com/lauris/awesome-scala
    icon: âš™ï¸
  - name: Selfhosted
    url: https://github.com/awesome-selfhosted/awesome-selfhosted
    icon: ğŸ–¥ï¸
  - name: Shell
    url: https://github.com/alebcay/awesome-shell
    icon: ğŸš
  - name: MacOS
    url:
      - https://github.com/serhii-londar/open-source-mac-os-apps
      - https://github.com/jaywcjlove/awesome-mac
    icon: ğŸ
  - name: Zig
    url: https://github.com/catdevnull/awesome-zig
    icon: ğŸ§©
  - name: TinyJS
    url: https://github.com/thoughtspile/awesome-tiny-js
    icon: ğŸŒŸ
  - name: MachineLearning
    url: https://github.com/josephmisiti/awesome-machine-learning
    icon: ğŸ¤–
  - name: Awesome
    url: https://github.com/sindresorhus/awesome
    icon: ğŸ†’
